# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd7c149bd78dabacc904dffd0061cd05f8609f0e96e33ba21134f760a07ba24d6143865b88fb4ce3b2789527df1767be8751ce2917bf57f81f3c28a445d40c52

test:
  secret_key_base: ad820b0b0483cd26eaab42bf7f1f6932602cc87006ef90d361c9d68ef8cbb37d46fecb0138edf9c97ea2fd6337b58098dd02da575af96ad41a119effb8285151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
